
# Path to image for classify
img_path: /home/artem/pdd/script_test/xloros/xloros.jpg

# Path to feature extractor model 
feature_extractor: triplet.pt

# Path to classifier model 
classifier: knn_model.sav

# Path to file with class names
class_names: classname.txt