
#Random seed
random_seed: 13

# Cudnn_deterministic
cudnn_deterministic: True 

# Number of classes to classify
num_classes: 15

# Path to the archive with data
data_zip_path: 'archive_full.zip'

# Path to the dircectory to save files
data_save_path: 'data/'

# The size of the test data as a percentage
test_size: 0.2

# Number of sample per draw ( to increase probability to
#               contain valid triplets in a batch )
n_sample: 3

# Batch size
batch_size: 12

# Count of epochs:
epochs: 1000

# Path to save the plot with embeddings
plot_embeddings_img: './PDD.png'

# Path to save model parameters 
model_save_path: 'triplet_model_param.pt'

# Path to save optimizer parameters
optim_save_path: 'triplet_model_param.pt'

# Colors of points on plot 
point_colors: ['#00ffff', '#000000', '#0000ff', '#ff00ff',
          '#808080', '#008000', '#00ff00', '#800000',
          '#000080', '#808000', '#800080', '#ff0000',
          '#c0c0c0', '#008080', '#ffff00']

knn_metric: 'cosine'
         